# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Zipcode', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.IntegerField(null=True)),
                ('SecurityCode', models.IntegerField(null=True)),
                ('ExpMonth', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True)),
                ('ExpYear', models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2017, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('numAvailable', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineItemTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Item')),
                ('lineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.LineItem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('custProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile')),
                ('payMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CreditCard')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OR', 'Ordered'), ('SP', 'Shipped'), ('DE', 'Delivered')], default='OR', max_length=5)),
                ('estimated_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('shipped_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Zipcode', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('custProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Timestamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Buy milk, wash dog etc', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.TodoList'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Order'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='custProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='custProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile'),
        ),
    ]
