# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-04 14:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Zipcode', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.IntegerField(null=True)),
                ('SecurityCode', models.IntegerField(null=True)),
                ('ExpMonth', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True)),
                ('ExpYear', models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2017, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('numAvailable', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.IntegerField(null=True)),
                ('subTotal', models.IntegerField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='LineItemTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Item')),
                ('lineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.LineItem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('SH', 'SHIPPED'), ('IN', 'INVOICED')], default='PE', max_length=10)),
                ('total_cost', models.FloatField(default=0)),
                ('billAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.BillingAddress')),
                ('custProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile')),
                ('payMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CreditCard')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PI', 'Pick'), ('PA', 'Pack'), ('SH', 'Ship'), ('RI', 'RETURN INITIATED'), ('RR', 'RETURN RECEIVED')], default='PI', max_length=5)),
                ('estimated_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('shipped_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('litem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.LineItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Zipcode', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('custProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[('Every Week', 1), ('Every 2 Weeks', 2), ('Every 3 Weeks', 3), ('Every Month', 4), ('Every 2 Months', 5), ('Every 3 Months', 6)], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Buy milk, wash dog etc', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.TodoList'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='custProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='custProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile'),
        ),
    ]
