# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTest', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
