# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0004_customerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='custProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='custProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile'),
        ),
    ]
