# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0005_auto_20170206_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.IntegerField()),
                ('SecurityCode', models.IntegerField()),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('custProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.CustomerProfile')),
            ],
        ),
    ]
