# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0006_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='birthdate',
            field=models.IntegerField(choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992')], default=1900),
        ),
    ]
