# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0011_order_shipment_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
