# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0012_auto_20170208_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='Street',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
