# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0015_auto_20170209_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='ExpMonth',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, null=True),
        ),
    ]
