# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0017_auto_20170209_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='ExpMonth',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
    ]
