# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0018_auto_20170209_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sex', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='demo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='school',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
