# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-17 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0019_auto_20170210_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
