# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0021_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineItemTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='lineitem',
        ),
        migrations.AlterField(
            model_name='item',
            name='SKU',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='lineitemtable',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Item'),
        ),
        migrations.AddField(
            model_name='lineitemtable',
            name='lineItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.LineItem'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon_Core.Order'),
        ),
    ]
