# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon_Core', '0022_auto_20170217_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to='items/%Y/%m/%d/'),
        ),
    ]
